# Generated by Django 4.2.1 on 2023-05-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250, unique=True)),
                ('price', models.FloatField(unique=True)),
                ('decription', models.TextField(unique=True)),
                ('num_of_bedrooms', models.IntegerField()),
                ('image', models.ImageField(default=True, unique=True, upload_to='images/')),
            ],
        ),
    ]
