# Generated by Django 4.2.1 on 2023-05-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
